<?php

return [
    'step1' => [
        'torres_island' => [
            1 => 'Neither Aboriginal nor Torres Strait Islander',
            2 => 'Aboriginal',
            3 => 'Torres Strait Islander',
            4 => 'Aboriginal and Torres Strait Islander',
        ],
        'disabilities' => [
            1 => 'Hearing/deaf',
            2 => 'Physical',
            3 => 'Intellectual',
            4 => 'Learning',
            5 => 'Mental illness',
            6 => 'Acquired brain impairment',
            7 => 'Vision',
            8 => 'Medical condition',
            9 => 'Other',
        ],
        'industry1' => [
            1 => 'Agriculture, forestry and fishing',
            2 => 'Mining',
            3 => 'Manufacturing',
            4 => 'Electricity, gas, water and waste services',
            5 => 'Construction',
            6 => 'Wholesale trade',
            7 => 'Retail trade',
            8 => 'Accommodation and food services',
            9 => 'Transport, postal and warehousing',
            10 => 'Information media and telecommunications',
            11 => 'Financial and insurance services',
            12 => 'Rental, hiring and real estate services',
            13 => 'Professional, scientific and technical services',
            14 => 'Administrative and support services',
            15 => 'Public administration and safety',
            16 => 'Education and training',
            17 => 'Health care and social assistance',
            18 => 'Arts and recreation services',
            19 => 'Other services',
        ],
        'industry2' => [
            1 => 'Manager',
            2 => 'Professionals',
            3 => 'Technicians and trades workers',
            4 => 'Community and personal service workers',
            5 => 'Clerical and administrative workers',
            6 => 'Sales workers',
            7 => 'Machinery operators and drivers',
            8 => 'Labourers',
            9 => 'Other',
        ],
        'employment' => [
            1 => 'Full time employee',
            2 => 'Part time employee',
            3 => 'Self employed - not employing others',
            4 => 'Self employed - employing others',
            5 => 'Employed - unpaid worker in a family business',
            6 => 'Unemployed - seeking full time work',
            7 => 'Unemployed - seeking part time work',
            8 => 'Not employed - not seeking employment',
        ],
    ],
    'step2' => [
        'school_level' => [
            1 => 'Completed Year 12',
            2 => 'Completed Year 11',
            3 => 'Completed Year 10',
            4 => 'Year 9 or equivalent',
            5 => 'Year 8 or below',
            6 => 'Did not go to School',
        ],
        'secondary_level' => [
            'yes' => 'Yes',
            'no' => 'No',
        ],
        'education_from' => [2 => 'Australian Qualification', 3 => 'Australian equivalent', 4 => 'International'],
    ],
    'step4' => [
        'study_reason' => [
            1 => 'To get a job',
            2 => 'To develop my existing business',
            3 => 'To start my own business',
            4 => 'To try for a different career',
            5 => 'To get a better job or promotion',
            6 => 'It was a requirement of my job',
            7 => 'I wanted extra skills for my job',
            8 => 'To get into another course of study',
            9 => 'For personal interest or self-development',
            11 => 'To get skills for community/voluntary work',
            10 => 'Other reasons',
        ],
        'nominate_usi' => [
            1 => 'Email',
            2 => 'Mobile',
            3 => 'Mail',
        ],
        'document_type' => [
            1 => 'Drivers Licence',
            2 => 'Medicare Card',
            3 => 'Australian Passport',
            4 => 'Full Birth Certificate (Australian)',
            5 => 'Immicard',
            6 => 'Citizenship Certificate',
            7 => 'Certificate of Registration by Descent',
            8 => 'Visa (with non-Australian Passport of International Students)',
        ],
    ],
];
